const actions = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CARS_LOADED: "CARS_LOADED",
  EXCHANGE_LOADED: "EXCHANGE_LOADED",
  UPDATE_CART: "UPDATE_CART",
  EMPTY_CART: "EMPTY_CART"
};

export default actions;
